### PR TITLE
[Fixes #30] ProcessBot and ServiceBot tests

### LINKED ISSUE #30: [Smoke Tests] ProcessBot and ServiceBot
Missing tests for ProcessBot and ServiceBot.

### PR DESCRIPTION
**Pull request by gioscarda**
This PR fixes #30 .

ProcessBot and ServiceBot tests added.

### CODE REVIEW

**Comment by afabiani** [comment]
@gioscarda I see some conflicts

**Comment by gioscarda** [comment]
@afabiani , yes, I will update my PR soon to avoid conflicts

**Comment by afabiani** [comment]
@gioscarda for some reasons Travis never ends

**Comment by gioscarda** [comment]
@afabiani I'm investigating on it, It seems some threads are still alive when the test ends

**Pull request merged**
